import {useState} from 'react';
import FeatureIntro from '../components/FeatureIntro';
import {Loading,ErrorBox,BackendResponse} from '../components/Feedback';
import {callFeature,loadSession,saveSession} from '../lib/api';
import Icons from '../components/Icons';
export default function Quiz(){
  const [lang,setLang]=useState('en');const [quiz,setQuiz]=useState(()=>loadSession('tadabbur_quiz',null));const [answers,setAnswers]=useState({});const [result,setResult]=useState(null);const [response,setResponse]=useState(null);const [loading,setLoading]=useState(false);const [err,setErr]=useState(null);const studied=loadSession('tadabbur_learning_plan',null);
  async function generate(){setLoading(true);setErr(null);setResponse(null);setResult(null);try{const r=await callFeature('quiz',{requested_feature:'quiz',action:'generate',language:lang,studied_material:studied});setResponse(r);setQuiz(r.data);saveSession('tadabbur_quiz',r.data);setAnswers({})}catch(x){setErr(x)}finally{setLoading(false)}}
  async function submit(){const qs=quiz?.questions||quiz?.quiz?.questions||[];if(!Array.isArray(qs)||qs.length!==5){setErr(new Error('The quiz must contain exactly five questions before submission.'));return}if(qs.some((_,i)=>answers[i]===undefined)){setErr(new Error('Please answer all five questions before submitting.'));return}setLoading(true);setErr(null);setResponse(null);try{const r=await callFeature('quiz',{requested_feature:'quiz',action:'submit',language:lang,quiz_id:quiz?.quiz_id,answers:qs.map((q,i)=>({question_id:q.question_id||q.id||String(i+1),selected_option:answers[i]}))});setResponse(r);setResult(r.data)}catch(x){setErr(x)}finally{setLoading(false)}}
  const qs=Array.isArray(quiz?.questions)?quiz.questions:(Array.isArray(quiz?.quiz?.questions)?quiz.quiz.questions:[]);
  return <section className="page"><FeatureIntro number="05" label="Assessment" title="Quiz" text="Five questions based on material from the current learning flow. The quiz workflow owns answer sealing and scoring."/>
    <div className="quiz-top"><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="ur">Urdu</option><option value="roman_ur">Roman Urdu</option></select><button className="btn outline" onClick={generate} disabled={loading}>{qs.length?'Generate new quiz':'Generate 5 questions'}</button></div>
    {!qs.length&&<div className="empty"><h3>{studied?'Ready for assessment':'Study first, then quiz'}</h3><p>{studied?'Use the material from the current Learning Plan to generate the five-question assessment.':'Create a Learning Plan first so the quiz has current studied material.'}</p></div>}
    {loading&&<Loading>Preparing your assessment…</Loading>}{err&&<><ErrorBox message={err.message}/><BackendResponse error={err}/></>}
    {qs.length===5&&!result&&!loading&&<div className="quiz-list">{qs.map((q,i)=><article className="question" key={q.question_id||q.id||i}><div className="qnum">{i+1}</div><div className="qcontent"><h3>{q.question||q.prompt}</h3><div className="options">{(Array.isArray(q.options)?q.options:[]).slice(0,4).map((o,j)=>{const val=o?.value||o?.option_id||o?.id||String.fromCharCode(65+j);const text=o?.text||o?.label||o;return <label className={answers[i]===val?'selected':''} key={val}><input type="radio" name={`q-${i}`} checked={answers[i]===val} onChange={()=>setAnswers(a=>({...a,[i]:val}))}/><b>{String.fromCharCode(65+j)}</b><span>{text}</span></label>})}</div></div></article>)}<button className="btn green submit-quiz" onClick={submit}>Submit quiz <Icons name="arrow" size={16}/></button></div>}
    {result&&!loading&&<div className="result-card"><span className="eyebrow">Assessment complete</span><h2>{result?.score!==undefined?`${result.score} / 5`:'Submitted'}</h2><p>{result?.summary||'Your five answers have been evaluated.'}</p>{(Array.isArray(result?.explanations)?result.explanations:Array.isArray(result?.result?.questions)?result.result.questions:[]).map((x,i)=><div className="review-row" key={i}><strong>{i+1}. {x.correct?'Correct':'Review'}</strong><p>{x.explanation||x.message||''}</p></div>)}</div>}
    {response&&!err&&<BackendResponse response={response}/>} 
  </section>
}
